name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your main branch name (could be 'master')
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # or your main branch name

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install API dependencies
        run: |
          if [ -d "api" ]; then
            cd api
            npm install
            cd ..
          fi
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"    # App source code path
          api_location: "api"  # API source code path
          app_artifact_location: "."  # Built app output path - use root directory
          skip_app_build: true  # Skip trying to build the app since it's already built